apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-vcluster
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.20.0-beta.6
    helm:
      releaseName: demo-vcluster
      valueFiles:
        - vcluster.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-vcluster
